### ISSUE TITLE
Trouble with keybindings

### ISSUE THREAD

**Issue by LYF610400210** [maxbrunsfeld/atom-nrepl#11]
I have trouble using the shortcut key `ctrl-alt-e` to trigger `nrepl:eval` after I select an expression in the editor, but the command palette works fine.

```
X nrepl:eval    .atom-workspace    C:\...\.atom\packages\nrepl\keymaps\nrepl.cson
```

Atom 0.199.0

**Comment by maxbrunsfeld** [comment]
@LYF610400210 thanks for the report. There was a typo in my keybindings file! This is fixed in `0.3.0`.
