### ISSUE TITLE
could not find nrepl port file

### ISSUE THREAD

**Issue by mneumark** [maxbrunsfeld/atom-nrepl#14]
I got an error that said:
`Connection Error - Could not find the nrepl port file`.

Any idea what that means?

**Comment by maxbrunsfeld** [comment]
Are you running `lein repl`? It should create that file.

**Comment by mneumark** [comment]
Yeah. I figured that out later. I might recommend mentioning that you need to run it when this error occurs.

**Comment by maxbrunsfeld** [comment]
Yeah, that seems reasonable.
