### ISSUE TITLE
Not giving back focus

### ISSUE THREAD

**Issue by pistacchio** [maxbrunsfeld/atom-nrepl#18]
After the panel with the result is shown, when you hit "Esc" it closes but doesn't give the focus back to current editing window

**Comment by lincoln-b** [comment]
Came here to post this issue as well. Bad enough to be a non-starter.

**Comment by maxbrunsfeld** [comment]
Sorry about this, folks. I unfortunately don't have time to work on this package anymore, and I haven't used clojure in a long time. I'll add a note about this in the README, but while I have you here, are any of you interested in taking over maintainership of this package?

**Comment by lwb4** [comment]
Understandable. Sadly, I don't have enough knowledge to take it over, and Proto-REPL gets the job done well enough so I'm just using that.

**Comment by maxbrunsfeld** [comment]
Ok, great. I'm glad to hear there's another Atom package that does a good job of this!
